package com.ns.tcpframework.reqeustHandlers;

import com.ns.tcpframework.HTTPRequest;
import com.ns.tcpframework.HTTPResponse;
import com.ns.tcpframework.RouteCommand;

import java.util.HashMap;

/**
 * A request handler that routes requests to specific commands based on URL paths.
 * <p>
 * This class extends {@link RequestHandler} to provide route-based request handling,
 * where different URL paths can be mapped to different {@link RouteCommand} implementations.
 * It supports both exact path matching and parameterized routes with path variables.
 * <p>
 * Route matching behavior:
 * <ul>
 *   <li><b>Exact match</b>: If the request path exactly matches a registered route,
 *       that route's command is executed</li>
 *   <li><b>Parameterized match</b>: If no exact match is found, the handler attempts
 *       to match against a normalized path pattern ending with {@code /:id}</li>
 * </ul>
 * <p>
 * Example usage:
 * <pre>
 * RouteBasedHandler handler = new RouteBasedHandler();
 * handler.routes.put("/api/users", getUsersCommand);
 * handler.routes.put("/api/users/:id", getUserByIdCommand);
 * </pre>
 *
 * @see RequestHandler
 * @see RouteCommand
 */
public class RouteBasedHandler extends RequestHandler {
    /**
     * Map of URL paths to their corresponding route commands.
     * <p>
     * Keys are URL path strings (e.g., "/api/users" or "/api/users/:id").
     * Values are {@link RouteCommand} implementations that handle the requests
     * for those paths.
     * <p>
     * This field is protected to allow subclasses to register routes directly.
     */
    protected HashMap<String, RouteCommand> routes = new HashMap<>();

    /**
     * Handles an HTTP request by routing it to the appropriate command.
     * <p>
     * This method implements a two-step routing strategy:
     * <ol>
     *   <li>First, attempts to find an exact match for the request path</li>
     *   <li>If no exact match exists, normalizes the path by replacing the last
     *       path segment with {@code :id} and attempts to match against parameterized routes</li>
     * </ol>
     * <p>
     * Path normalization example:
     * <ul>
     *   <li>{@code /api/users/123} → {@code /api/users/:id}</li>
     *   <li>{@code /api/products/456} → {@code /api/products/:id}</li>
     * </ul>
     *
     * @param request The HTTP request to handle.
     * @return The HTTP response generated by the matched route command.
     * @throws Exception if no matching route is found or if the route command
     *                   throws an exception during execution.
     * @throws NullPointerException if no route matches and the normalized path
     *                              is also not found in the routes map.
     */
    @Override
    public HTTPResponse handle(HTTPRequest request) throws Exception {
        HTTPResponse response = null;

        String normalizedPath = request.getRequestHead().substring(0,request.getRequestHead().lastIndexOf("/"))+"/:id";

        if (!routes.containsKey(request.getRequestHead())){
            response = routes.get(normalizedPath).run(request);

        } else {
            response = routes.get(request.getRequestHead()).run(request);
        }

        return response;
    }
}
